spring.application.name=letswatch

# H2 Adatbázis beállítások (Kettes szinthez)
spring.datasource.url=jdbc:h2:mem:letswatchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hogy lássuk a konzolon, mit ügyködik a háttérben az adatbázissal
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 Konzolt elérhet?vé tesszük a böngész?b?l
spring.h2.console.enabled=true